development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= redis://:#{ENV["REDIS_PASSWORD"]}@#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/0 %>
  channel_prefix: myapp_production
